### ISSUE TITLE
Write the code for the ruby interface of SymEngine C constants 

### ISSUE THREAD

**Issue by abinashmeher999** [symengine/symengine.rb#11]
The aim is to write the extension code for SymEngine C API constants (https://github.com/symengine/symengine/pull/781) using the Ruby C API (refer [Beginner-Contributor-Guide---Ruby-Extensions](https://github.com/symengine/symengine/wiki/Beginner-Contributor-Guide---Ruby-Extensions)) such that it passes the tests written as a part of https://github.com/symengine/symengine.rb/issues/10

After this symengine.rb will support commonly used constants like pi, E (base of natural logarithm), etc.

**Comment by isuruf** [comment]
Closed via #14
