### ISSUE TITLE
Wrap SymEngine::ascii_art() and replace the current function

### ISSUE THREAD

**Issue by abinashmeher999** [symengine/symengine.rb#13]
Refer https://github.com/symengine/symengine/pull/797/ and wrap it to replace the code [here](https://github.com/symengine/symengine.rb/blob/master/lib/symengine.rb#L6). It will also involve writing the C wrapper for the function.

**Comment by codeworm96** [comment]
Now in the C++ library, the ascii_art returns a string instead of printing it out. Should the ruby wrapper modify its behavior accordingly?

**Comment by certik** [comment]
@codeworm96 probably. The user can easily print by hand.
