### ISSUE TITLE
Remove Rational initialise method

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine.rb#19]
Since the result may not be a rational this should be removed and a function should be introduced.

For ex:
```
a = Rational('2/1')
b = SymEngine::Rational.new(a)
```
`b` should not be a `SymEngine::Rational`, but a `SymEngine:Integer`

**Comment by badcoderparashar** [comment]
i have a suggestion if a= Rational( 'p/q' )
if we can check that if p%q=0 or not we can show it is rational or integer
just working on it

**Comment by rajithv** [comment]
While I was looking for a way to have this in Ruby, I came across the observation that in Ruby Complex and Ruby Rational, something like `2/1` are given as Rational. (The same for `2+0i` as Complex)

```
2.1.8 :005 > a = Rational('2/1')
 => (2/1) 
2.1.8 :006 > a.class
 => Rational 
```

How should I proceed?

**Comment by isuruf** [comment]
You should remove the initialize method and then expose sympify method to ruby. So that `sympify(1/2)` would give a SymEngine rational and `sympify(2/1)` gives a SymEngine integer. That's what `sympify` already does, you just need to expose it to ruby.

**Comment by rajithv** [comment]
@isuruf okay. So, say for an example, one could use it as:

```
a = SymEngine::sympify(1/2)
a.class # returns SymEngine::Rational

a = SymEngine::sympify(2/1)
a.class # returns SymEngine::Integer

b = Rational('2/1')
b.class # returns Rational
a = SymEngine::sympify(b)
a.class # returns SymEngine::Integer
```

right?

**Comment by isuruf** [comment]
Not really. 
Following would be disallowed as this issue says.
```
b = Rational('2/1')
```

**Comment by rajithv** [comment]
well, it's Ruby's `Rational` class .. cannot disallow that.. right?

**Comment by isuruf** [comment]
Sorry. I thought it was `SymEngine::Rational`. You are right. That's exactly what we want
