### ISSUE TITLE
Rewrite FindRuby.cmake

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine.rb#2]
The current `FindRuby.cmake` supports only ruby upto 2.1. 

Instead of this file, an equivalent of [FindPython.cmake](https://github.com/symengine/symengine.py/blob/master/cmake/FindPython.cmake) should be written

**Comment by abinashmeher999** [comment]
I think the [Kitware's repo](https://github.com/Kitware/CMake) can also benefit from this. I thought of creating a similar issue there too, but they don't seem to have enabled that in their repo.

**Comment by isuruf** [comment]
It is similar to FindPython.cmake and setting RUBY_EXECUTABLE fixes it.
