### ISSUE TITLE
Expose sympify function to ruby

### ISSUE THREAD

**Issue by isuruf** [symengine/symengine.rb#21]
This can be accessed in C only.

**Comment by badcoderparashar** [comment]
i want to work on this

**Comment by badcoderparashar** [comment]
can you guide me

**Comment by isuruf** [comment]
Sure. What do you need to know?

**Comment by badcoderparashar** [comment]
as i am a beginner can you tell me whereto start

**Comment by abinashmeher999** [comment]
Start from here https://github.com/symengine/symengine/wiki/Beginner-Contributor-Guide---Ruby-Extensions and here https://github.com/symengine/symengine.rb/blob/master/ext/symengine/symengine_macros.c#L4
