### ISSUE TITLE
Differentiation would be awesome

### ISSUE THREAD

**Issue by mohawkjohn** [symengine/symengine.rb#29]
I realize there's a lengthy roadmap for this gem / for GSoC this year, but I'd like to vote for the differentiation functionalities to be exposed ASAP. I'd actually use these pretty much immediately. =)

**Comment by abinashmeher999** [comment]
Differentiation works for simple cases. Like demonstrated [here](https://github.com/symengine/symengine.rb/blob/master/notebooks/differentiation_example.ipynb). The PR for functions is underway. We will be able to see more functionalities as soon as they are in.

**Comment by mohawkjohn** [comment]
Oh, wonderful! I wasn't sure where the examples are. A link on the readme might be nice. That's awesome. =D
