### ISSUE TITLE
Expose lambdify

### ISSUE THREAD

**Issue by mohawkjohn** [symengine/symengine.rb#35]
Trying the differentiation notebook example, and I'd really like to be able to lambdify the answer.

As a side note, I *believe* this should be super easy in Ruby for *some* expressions. For example, with the answer given in the differentiation notebook, I just do:

```
my_lambda = lambda { |x,p| eval(answer.to_s) }
```

Of course, that won't work if it's got any kind of built-in functions in it, since in Ruby you need to do `Math.cos` instead of just `cos`.

**Comment by isuruf** [comment]
There are 2 options,
1. Expose symengine's lambda_double which can output a double
2. Extend StrPrinter to print `Math.cos` instead of `Math.sin`
I like both options. What do you think?

@rajithv, you mentioned option 1 in your GSoC proposal, do you want to start it now?

**Comment by isuruf** [comment]
Closed via #61
