### ISSUE TITLE
RubyDataScience

### ISSUE THREAD

**Issue by arbox** [symengine/symengine.rb#68]
Dear contributors,

we've recently added `symengine`  to our upcoming RubyDataScience list: https://github.com/arbox/data-science-with-ruby

In order to connect all Ruby & Data Science related projects we introduced the `rubydatascience` topic on GitHub.

Please consider adding this topic to your repository as well so that the Ruby community can discover this project faster :smiley: 

Thank you in advance!

**Comment by abinashmeher999** [comment]
Sure thing! :smiley:  

Thanks for making the gem a part of the RubyDataScience list. Hope we get to see some really cool projects from the community using `symengine.rb`.

@isuruf Could you please add the topic along with other ones used with SymEngine? I am unable to edit them.

**Comment by arbox** [comment]
Help us to build the community together. Tell people about your use cases, it's always very interesting. Pull Request are welcome!

**Comment by certik** [comment]
@arbox I think it's there. Can you confirm please?

**Comment by arbox** [comment]
@certik it's there!

**Comment by certik** [comment]
@arbox thanks!
